import React, { useState, useEffect, useRef } from 'react';
import { SopStepType } from '../types';
import html2canvas from 'html2canvas';

interface FlowchartProps {
  steps: SopStepType[];
  onStepHover: (stepId: number | null) => void;
}

// NOTE: This is a simplified flowchart visualization using divs and CSS.
// In a production app, a library like React Flow would be used for more advanced features.
const Flowchart: React.FC<FlowchartProps> = ({ steps, onStepHover }) => {
  const [completedSteps, setCompletedSteps] = useState<Record<number, boolean>>({});
  const flowchartRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    // Reset completion status when steps change
    setCompletedSteps({});
  }, [steps]);

  const toggleStepCompletion = (stepId: number) => {
    setCompletedSteps(prev => ({ ...prev, [stepId]: !prev[stepId] }));
  };
  
  const handleExport = async () => {
    if (!flowchartRef.current) {
        alert('Could not find flowchart to export.');
        return;
    }

    try {
        const canvas = await html2canvas(flowchartRef.current, {
            useCORS: true,
            logging: true,
            // You might need to adjust these options based on your specific styling and content
            // For example, to handle scrolling content, you might need to set scrollY and windowHeight
        });

        const image = canvas.toDataURL("image/png");
        const link = document.createElement('a');
        link.href = image;
        link.download = 'sop_flowchart.png';
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
    } catch (error) {
        console.error("Error exporting flowchart:", error);
        alert('Failed to download flowchart. Please try again.');
    }
  };

  if (steps.length === 0) {
    return (
        <div className="bg-white dark:bg-gray-800 rounded-lg p-6 h-full flex flex-col items-center justify-center">
            <h2 className="text-xl font-bold mb-4 text-center">SOP Flowchart</h2>
            <p className="text-gray-500 dark:text-gray-400 text-center">Your SOP flowchart will appear here once generated by the AI.</p>
        </div>
    );
  }

  return (
    <div className="bg-white dark:bg-gray-800 rounded-lg p-6 h-full flex flex-col">
        <div className="flex justify-between items-center mb-6 no-print">
            <h2 className="text-xl font-bold">SOP Flowchart</h2>
            <button
                onClick={handleExport}
                className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition"
            >
                Download Flowchart
            </button>
        </div>
        <div id="flowchart-print-area" ref={flowchartRef} className="flex-grow overflow-auto p-4">
            <div className="flex flex-col items-center space-y-2">
            {steps.map((step, index) => (
                <React.Fragment key={step.id}>
                <div 
                    onMouseEnter={() => onStepHover(step.id)}
                    onMouseLeave={() => onStepHover(null)}
                    className={`w-full max-w-md p-4 rounded-lg shadow-md border-l-4 cursor-pointer ${completedSteps[step.id] ? 'bg-green-100 dark:bg-green-900 border-green-500' : 'bg-gray-100 dark:bg-gray-700 border-gray-500'} transition-colors`}
                >
                    <div className="flex items-center justify-between">
                    <span className="font-semibold text-gray-800 dark:text-gray-200">{step.id}. {step.title}</span>
                    <label className="flex items-center cursor-pointer">
                        <div className="relative">
                        <input type="checkbox" className="sr-only" checked={!!completedSteps[step.id]} onChange={() => toggleStepCompletion(step.id)} />
                        <div className="block bg-gray-300 dark:bg-gray-600 w-10 h-6 rounded-full"></div>
                        <div className={`dot absolute left-1 top-1 bg-white w-4 h-4 rounded-full transition-transform ${completedSteps[step.id] ? 'transform translate-x-full bg-green-500' : ''}`}></div>
                        </div>
                    </label>
                    </div>
                </div>
                {index < steps.length - 1 && (
                    <div className="h-8 w-1 bg-gray-300 dark:bg-gray-600"></div>
                )}
                </React.Fragment>
            ))}
            </div>
      </div>
    </div>
  );
};

export default Flowchart;